### ISSUE TITLE
Something Else?

### ISSUE THREAD

**Issue by obedm503** [devsnek/proposal-standard-debug#1]
I'm curious, wouldn't the pipe operator solve this?
```js
function doSomething(a) {
  let b = dbg!(a + costlyOperation()) * 2;
  // ...
}
// with pipe 
const debug = (value) => {console.log(value); return value;}
function doSomething(a) {
  let b = ((a + costlyOperation()) |> debug) * 2;
  // ...
}
```
I know this is an early proposal. I just want to understand what it intends to accomplish.
Is it just introducing a `debug` function that can be easily written on one line? 
Or more complex debugging features that are not currently available?

**Comment by devsnek** [comment]
part of the motivation here is an api that is available anywhere that you're writing js.

**Comment by obedm503** [comment]
Does a one-liner function require going through the tc39 process, and adding more baggage to the language?

Anyways, thanks for the answer.

**Comment by hax** [comment]
Of coz we can use pipeline op, but unfortunately, pipeline op require u to write many parens.

The old bind operator proposal need less parens:

```js
function doSomething(a) {
  let b = (a + costlyOperation())::debug() * 2;
  // ...
}
```

The main difference of `dbg!(v)` and `v::dbg()` is the order, I can see each have their pros and cons. Anyway, I like the idea of having a debug api!
