### ISSUE TITLE
Debugging promises

### ISSUE THREAD

**Issue by legendecas** [devsnek/proposal-standard-debug#2]
Noticed that console logging promises' results were listed in the problems. I'm curious about how the proposed solution resolves the problems raised regarding the promises -- however, I didn't find some explanation in the README.

**Comment by hax** [comment]
There is a slide page for that.

```js
foo().then(bar => dbg!(bar).baz())
```

I guess we could also have:
```js
foo()
  .then(dbg!)
  .then(bar => bar.baz())
```

**Comment by legendecas** [comment]
Note that in the problem in the README:

```js
foo()
  .then((bar) => bar.baz());
  
foo()
  .then((bar) => {    // ❌ relatively large refactoring for logging a variable
    console.log(bar);
    return bar.baz();
  });
  
foo()
  .then((bar) => {    // ❌ lots of extra code, could change tick ordering
    console.log(bar);
    return bar;
  })
  .then((bar) => bar.baz());
```

The proposed solution doesn't seem to do any seeable difference in the case with console.log. Do I get it right?

**Comment by devsnek** [comment]
The demonstrated solution, as hax posted, is `foo().then(bar => dbg!(bar).baz())`
