### ISSUE TITLE
how about this 

### ISSUE THREAD

**Issue by zhangenming** [devsnek/proposal-standard-debug#7]
```js
Object.defineProperty(Object.prototype, 'log', {get(){console.log(this);return this}})


var a = [1,2,3,4].log
```

**Comment by ljharb** [comment]
Any new property on Object.prototype would break a ton of things, and also wouldn't work on null objects (`Object.create(null)`) or primitives.

**Comment by zhangenming** [comment]
I mean Something like this syntax, [1,2,3,4].log

**Comment by devsnek** [comment]
I don't see how this would be workable, we can't shadow property access.
